Fix NoMethodError error on Ruby 2.4 and older. Fixes https://github.com/kjvarga/sitemap_generator/issues/352
NoMethodError: private method `open' called for URI:Module was raised on older rubies as URI.open was added only in Ruby 2.5: https://rubyreferences.github.io/rubychanges/2.5.html#network-and-web